language: csharp
sudo: false
dist: xenial
mono: none
matrix:
  include:
    - dotnet: 2.2
    - dotnet: 2.1
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
  - make install
script:
  - make all
notifications:
  email: false
